claim:
  vertexpand: false
  blocklimits:
    enabled: false
    limits: {}
    minimal:
      volume: 0
      horizontal: 0
      vertical: 0
regionprotect:
  flow:
    lava: false
    water: false
    other: false
  fire:
    spread:
      toregion: false
      inregion: false
    burn: false
  explosion:
    block: false
    entity: false
autoflags:
  enabled: false
  show-messages: false
  flags: {}
restrictcommands:
  enabled: false
  commands: []
extendedwewand: false
misc:
  pvpmode: default
